id: P010473
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ6588
  title: འཇིག་རྟེན་དབང་ཕྱུག་དྲི་མེད་ཀུན་ལྡན་གྱི་ལོ་རྒྱུས་
  author: ''
  volumes:
    f57258c45564417694bb8a7858fa712f:
      image_group_id: I1KG1387
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
